config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "tasks", to: "tasks#index"
  get "tasks/new", to: "tasks#new",  as: :new_task
  post "tasks", to: "tasks#create"  
  get "tasks/:id", to: "tasks#show", as: :task
  get    "tasks/:id/edit", to: "tasks#edit", as: :edit_task
  patch  "tasks/:id",      to: "tasks#update"
  delete "tasks/:id",      to: "tasks#destroy"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  validates :title, presence: true
  validates :details, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @lists = Task.all
  end

  def show
    @lists = Task.all
    @list = @lists.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
      @task = Task.new(task_params)
      if @task.save
        # @task.save
        redirect_to task_path(@task)
      else
        render 'tasks/new'
      end
  end

  def edit
    @tasks = Task.all
    @task = @tasks.find(params[:id])
  end

  def update
    @lists = Task.all
    @list = @lists.find(params[:id])
    if @list.update(task_params)
      redirect_to task_path(@list)
    else
      # render 'edit.html.erb'
      render :edit
    end
  end

  def destroy
    @lists = Task.all
    @list = @lists.find(params[:id])
    @list.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <% if @task.errors.full_messages.any? %>
    <% @task.errors.full_messages.each do |msg| %>
      <p class = "text-danger"><%= msg  %></p>
      <% end %>
    <% end %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.label :completed %>
  <%= f.check_box :completed, {}, true, false  %>
  <%= f.submit %>
<% end %>

app/views/tasks/edit.html.erb
<div class="container">
  <h1>Update <%= @task.title %></h1>
  <%= render 'tasks/form' %>
</div>

app/views/tasks/index.html.erb
<html>
<h1>My Tasks</h1>
<% @lists.each do |list| %>
  <li><% if list.completed %>
   <i class="fas fa-check-square"></i>
   <% else %>
   <i class="far fa-square"></i>
   <% end %>
  <%= link_to list.title,  task_path(list.id) %></li>
<% end %>
<p><%= link_to "create tasks",  new_task_path %></p>
<p><i class="fas fa-check-square"></i></p>
</html>

app/views/tasks/new.html.erb
<html>
  <h1>Add tasks</h1>
  <%= render 'tasks/form'  %>
</html>

app/views/tasks/show.html.erb
<html>
<h1><%= @list.title %></h1>
<p><%= @list.details %></p>
<p><%= @list.completed  %></p>
 <%= link_to "🗑", task_path(@list), method: :delete, data: { confirm: "Really delete #{@list.title}?" } %>
<li><%= link_to "edit", edit_task_path  %></li>
<li><%= link_to "Back to list",  tasks_path %></li>
</html>